In [1]:
import pandas as pd
import numpy as np

In [6]:
from utils import markov
from utils import shapley
from utils import heuristic

In [7]:
from utils.timer import Timer

## PRUEBA

In [2]:
data = [
    ['U1','C1',0],
    ['U2','C1',0],
    ['U3','C1',0],
    ['U4','C1',0],
    ['U5','C1',0],
    ['U6','C1',0],
    ['U7','C1',0],
    ['U8','C1',0],
    ['U9','C1',0],
    ['U10','C1',0],

    ['U6','C2',0],
    ['U7','C2',0],
    ['U8','C2',0],
    ['U9','C2',0],
    ['U10','C2',0],

    ['U11','C2',0],
    ['U12','C2',0],
    ['U13','C2',0],
    ['U14','C2',0],
    ['U15','C2',0],
    ['U16','C2',0],
    ['U17','C2',0],
    ['U18','C2',0],
    ['U19','C2',0],
    ['U20','C2',0],

    ['U6','C3',1],
    ['U7','C3',1],
    ['U8','C3',1],
    ['U9','C3',1],
    ['U10','C3',1],

    ['U11','C3',1],
    ['U12','C3',0],
    ['U13','C3',0],
    ['U14','C3',0],
    ['U15','C3',0],
    ['U16','C3',0],
    ['U17','C3',0],
    ['U18','C3',0],
    ['U19','C3',0],
    ['U20','C3',0],
    ]

In [15]:
import csv
with open('data_basic.csv', 'w') as f:
      
    write = csv.writer(f)
    write.writerows(data)

In [16]:
import pandas as pd
pd.read_csv("data_basic.csv")

Empty DataFrame
Columns: [['U1', 'C1', 0], ['U2', 'C1', 0], ['U3', 'C1', 0], ['U4', 'C1', 0], ['U5', 'C1', 0], ['U6', 'C1', 0], ['U7', 'C1', 0], ['U8', 'C1', 0], ['U9', 'C1', 0], ['U10', 'C1', 0], ['U6', 'C2', 0], ['U7', 'C2', 0], ['U8', 'C2', 0], ['U9', 'C2', 0], ['U10', 'C2', 0], ['U11', 'C2', 0], ['U12', 'C2', 0], ['U13', 'C2', 0], ['U14', 'C2', 0], ['U15', 'C2', 0], ['U16', 'C2', 0], ['U17', 'C2', 0], ['U18', 'C2', 0], ['U19', 'C2', 0], ['U20', 'C2', 0], ['U6', 'C3', 1], ['U7', 'C3', 1], ['U8', 'C3', 1], ['U9', 'C3', 1], ['U10', 'C3', 1], ['U11', 'C3', 1], ['U12', 'C3', 0], ['U13', 'C3', 0], ['U14', 'C3', 0], ['U15', 'C3', 0], ['U16', 'C3', 0], ['U17', 'C3', 0], ['U18', 'C3', 0], ['U19', 'C3', 0], ['U20', 'C3', 0]]
Index: []

[0 rows x 40 columns]

In [7]:
markov.markov_chain(data)

markov
C1  0.8571
C2  2.5714
C3  2.5714

In [4]:
shapley.shapley_value(data)

shapley
C1      1.6
C2      2.2
C3      2.2

In [5]:
heuristic.heuristic_models(data)

(       first
 canal       
 C1         5
 C2         1,
        last
 canal      
 C3        6,
          linear
 canal          
 C1     1.666667
 C2     2.166667
 C3     2.166667)

## MEJORA DE TIEMPOS

In [ ]:
from utils import markov

In [150]:
data = pd.read_csv("data_basic.csv",names=['user','channel','conversion'])
data.head(5)

user channel  conversion
0   U1      C1           0
1   U2      C1           0
2   U3      C1           0
3   U4      C1           0
4   U5      C1           0

In [151]:
caminos = markov.obtener_caminos_markov(data)

In [152]:
matriz_transicion = markov.calcular_matriz_transicion(caminos)

In [153]:
matriz_transicion

end      (start)  (conversion)  (null)   C1   C2   C3
start                                                
(start)      0.0           0.0     0.0  0.5  0.5  0.0
C1           0.0           0.0     0.5  0.0  0.5  0.0
C2           0.0           0.0     0.0  0.0  0.0  1.0
C3           0.0           0.4     0.6  0.0  0.0  0.0

In [154]:
matriz_transicion = matriz_transicion.append(pd.DataFrame(np.zeros((2,6)),columns=matriz_transicion.columns,index=['(conversion)','(null)']))

In [158]:
matriz_transicion = matriz_transicion[['(start)','C1','C2','C3','(conversion)','(null)']]

In [159]:
matriz_transicion

end           (start)   C1   C2   C3  (conversion)  (null)
(start)           0.0  0.5  0.5  0.0           0.0     0.0
C1                0.0  0.0  0.5  0.0           0.0     0.5
C2                0.0  0.0  0.0  1.0           0.0     0.0
C3                0.0  0.0  0.0  0.0           0.4     0.6
(conversion)      0.0  0.0  0.0  0.0           0.0     0.0
(null)            0.0  0.0  0.0  0.0           0.0     0.0

In [273]:
p_con = np.array([
    [0,0.5,0.5,0,0,0],
    [0,0,0.5,0,0,0.5],
    [0,0,0,1,0,0],
    [0,0,0,0,0.4,0.6],
    [0,0,0,0,1,0],
    [0,0,0,0,0,1]
])

In [283]:
p_con[:-2,:-2]

array([[0. , 0.5, 0.5, 0. ],
       [0. , 0. , 0.5, 0. ],
       [0. , 0. , 0. , 1. ],
       [0. , 0. , 0. , 0. ]])

In [274]:
p_sin = np.array([
    [0,0.5,0,0,0.5],
    [0,0,1,0,0],
    [0,0,0,0.4,0.6],
    [0,0,0,1,0],
    [0,0,0,0,1]
])

In [305]:
p_sin_inicial = np.array([0.5,0.5,0])

In [301]:
def calcular_p_stable(p,ver=False):
    q = p[:-2,:-2]
    if ver: print(f'matriz q:\n{q}\n')
    r = p[:-2,-2:]
    if ver: print(f'matriz r:\n{r}\n')
    i = np.eye(len(q))
    fm = np.linalg.inv(i-q)
    if ver: print(f'matriz fm:\n{fm}\n')
    p_stable = np.dot(fm,r)
    if ver: print(f'matriz p_stable:\n{p_stable}\n')

    return p_stable

In [302]:
p_stable_sin = calcular_p_stable(p_sin)
p_stable_con = calcular_p_stable(p_con)

In [303]:
p_stable_sin

array([[0.2, 0.8],
       [0.4, 0.6],
       [0.4, 0.6]])

In [304]:
p_stable_con

array([[0.3, 0.7],
       [0.2, 0.8],
       [0.4, 0.6],
       [0.4, 0.6]])

In [307]:
x_table_sin = np.dot(p_sin_inicial,p_stable_sin)

In [309]:
x_table_sin == p_stable_con[0]

array([ True,  True])

In [263]:
def generar_datos(s=3,m=2):
    q_r = np.random.dirichlet(np.ones(s+m),s)
    z = np.zeros((m,s))
    i = np.eye(m)
    p = np.append(q_r,np.append(z,i,axis=1),axis=0)
    return p

In [77]:
def inv_dot(matriz,vector):
    inv_diff = np.linalg.inv(np.identity(len(matriz)) - np.asarray(matriz))
    dot_prod = np.dot(inv_diff,np.asarray(vector))
    
    return dot_prod

In [78]:
def solve(matriz,vector):
    solved = np.linalg.solve(matriz,vector)
    
    return solved

In [79]:
matriz,vector = generar_datos(10)

with Timer():
    print("Metodo 1")
    metodo1 = inv_dot(matriz,vector)
with Timer():
    print("Metodo 2")
    metodo2 = solve(matriz,vector)
print()
print(metodo1)
print()
print(metodo2)

Metodo 1
Elapsed time: 0.0008 seconds
Metodo 2
Elapsed time: 0.0002 seconds

[[6.38144649e+15 6.20598366e+15]
 [6.38144649e+15 6.20598366e+15]
 [6.38144649e+15 6.20598366e+15]
 [6.38144649e+15 6.20598366e+15]
 [6.38144649e+15 6.20598366e+15]
 [6.38144649e+15 6.20598366e+15]
 [6.38144649e+15 6.20598366e+15]
 [6.38144649e+15 6.20598366e+15]
 [6.38144649e+15 6.20598366e+15]
 [6.38144649e+15 6.20598366e+15]]

[[-1.36618279 -2.12447656]
 [-8.69461101 -6.61446077]
 [ 0.93433023 -0.08513084]
 [ 6.16707065  4.42811963]
 [ 1.9852023   0.67733131]
 [-5.79599399 -2.7431356 ]
 [-0.24180605  1.62336161]
 [ 5.01393193  4.63820726]
 [-1.79840788  0.30110071]
 [ 3.07866221  1.25870541]]


In [23]:
for n in [1000,2000,5000,10000]:
    matriz = generar_matriz(n)
    with Timer():
        print(matriz.shape)
        resolver_matriz(matriz)

(1000, 1000)
Elapsed time: 0.1185 seconds
(2000, 2000)
Elapsed time: 0.9523 seconds
(5000, 5000)
Elapsed time: 8.7129 seconds
(10000, 10000)
Elapsed time: 71.9020 seconds
(20000, 20000)


In [ ]:
# armar matriz de convergencia (columnas finales)
removal_to_conv = data[['(null)','(conversion)']]

# armar matriz de canales (filas de canales)
removal_to_non_conv = data.drop(['(conversion)','(null)'],axis=1)

# calcular la inversa de (I - canales)
removal_inv_diff = np.linalg.inv(np.identity(len(removal_to_non_conv.columns)) - np.asarray(removal_to_non_conv))

# calcular producto matricial de la inversa y la de convergencia
removal_dot_prod = np.dot(removal_inv_diff, np.asarray(removal_to_conv))